package RequestReply.ComunicationType;

public enum ComunicationType
{
    SET_NEW_ORGANIZATION,
    SET_NEW_EVENT,
    SET_CLOSED_DAYS,
    SET_NEW_USER,
    EDIT_EVENT, 
    EDIT_PASSWORD, 
    GET_VOLUNTARIES,
    GET_EVENT,
    GET_USER_DATA,
    SET_DISPONIBILITY,
    DELETE_PLACE, 
    SET_VOLUNTARY_TO_EVENT,
    DELETE_VISIT_TYPE_FROM_PLACE, 
    DELETE_VOLUNTARY,
    SET_NEW_BENEFICIARY,
    DELETE_SUBSCRIBED_VISIT,
    SET_USER_TO_EVENT
}
