package Comunication.ComunicationType;

public enum ComunicationType
{
    DELETE_PLACE,
    DELETE_USER_SUBSCRIPTION_TO_EVENT,
    DELETE_VISIT,
    DELETE_VOLUNTARY,
    EDIT_VISITABLE_PLACES,
    GET_ALLOWED_VISIT_TYPES,
    GET_EVENT,
    GET_PERSONAL_DATA,
    GET_PLACES,
    GET_VOLUNTARIES,
    SET_CLOSED_DAYS,
    SET_DISPONIBILITY,
    SET_MAXIMUM_FRIENDS,
    SET_NEW_ORGANIZATION,
    SET_NEW_PASSWORD,
    SET_USER_SUBSCRIPTION_TO_EVENT,
    SET_VISITABLE_PLACES
}
