package Comunication.ComunicationType;

public enum ComunicationType
{
    DELETE_VOLUNTARY,
    GET_ALLOWED_VISIT_TYPES,
    GET_EVENT,
    GET_PLACES,
    GET_VOLUNTARIES,
    SET_CLOSED_DAYS,
    SET_DISPONIBILITY,
    SET_MAXIMUM_FRIENDS,
    SET_NEW_ORGANIZATION,
    SET_NEW_PASSWORD,
    SET_VISITABLE_PLACES
}
